config/routes.rb
Rails.application.routes.draw do
  resources :invoices, only: [:index, :update] do
    collection do
      get "invoice_number" => "invoices#get_invoice_number"
      get "synchronisation_of_invoices" => "invoices#synchronisation_of_invoices"
      post "fetch_invoices" => "invoices#fetch_invoices"
      post "custom_invoice" => "invoices#custom_invoice"
      get "new_employee" => "invoices#unregistered_employee"
      get "resync_status" => "invoices#resync_status"
      post "generate_invoices" => "invoices#generate_invoices", :as => :generate
      put "/recalculate" => "invoices#recalculate"
      get "/status", to: "invoices#invoice_status"
    end
  end

  match "invoices/:invoice_created_date" => "invoices#show", via: [:get, :pdf], :as => :invoice_pdf

  resources :employees, :only => [:create] do 
    collection do 
      post "/qualifications/:unregister_emp_id" => "employees#qualifications", as: :qualifications
      post "/family_details/:unregister_emp_id" => "employees#family_details", as: :family_details
      delete "/destroy_qualification/:unregister_emp_id" => "employees#destroy_qualification", as: :remove_qualification
      delete "/destroy_family_detail/:unregister_emp_id" => "employees#destroy_family_detail", as: :remove_family_detail
    end
  end

  namespace :reports do
    get "/" => "base#listing"
    resources :profitability_reports, only: [:index] do
      collection do 
        get "/divisions" => "profitability_reports#divisions_report", as: :divisions
        get "/projects" => "profitability_reports#projects_report", as: :projects
        get "/project" => "profitability_reports#specified_project_report", as: :project
        get "/division_based" => "profitability_reports#specified_division_report", as: :division_based
        get "/designations" => "profitability_reports#designations_report", as: :designations
        get "/employee_history" => "profitability_reports#employee_history_report", as: :employee_history
      end
    end
    resources :re_calculate_reports, only: [:index] do
      collection do 
        post "/calculate_profitability_reports" => "re_calculate_reports#calculate_profitability_reports"
      end
    end
  end

  resources :rates, only: [:index, :create, :update] do
    get "/sync_designations" => "rates#sync_designations", on: :collection
    get "/:designation_id/designation_rate_history" => "rates#designation_rate_history", on: :collection
  end

  resources :projects, only: [:index] do
    get "/sync_projects" => "projects#sync_projects", on: :collection
  end

  devise_for :users
  devise_scope :user do
    get "settings", to: "devise/registrations#edit"
  end

  get 'home/welcome'

  authenticated :user do
    root 'invoices#index', as: :authenticated_root
  end

  unauthenticated :user do
    devise_scope :user do 
      get "/", to: "devise/sessions#new"
    end
  end
end

app/models/employee/educationdetail.rb
# == Schema Information
#
# Table name: educationdetails
#
#  EmployeeID        :string(6)        default(""), not null
#  EducationDetailID :integer          not null, primary key
#  Qualification     :string(45)       default(""), not null
#  Institute         :string(45)       default(""), not null
#  YearFrom          :integer          not null
#  YearTo            :integer          not null
#  Type              :string(45)       default("Degree"), not null
#

class Employee::Educationdetail < ActiveRecord::Base
	belongs_to :employee, class_name: "Employee::Employeepersonaldetail", foreign_key: :EmployeeID, :dependent => :delete
	scope :for_unregistered_employee, -> (employee_id) { where("EmployeeID = '#{employee_id}'") }

	validates :Qualification, :Institute , :YearFrom, :YearTo, :Type, presence: true
	validate :qualification_length

	def qualification_length
		if self.Qualification
			errors.add :base, "Qualification length should not be more than 45" if self.Qualification.length >= 45
		end
	end
end

app/models/employee/employee_profitibility_report.rb
# == Schema Information
#
# Table name: employee_profitibility_reports
#
#  id                  :integer          not null, primary key
#  employee_id         :string(255)      default(""), not null
#  employee_name       :string(255)      default(""), not null
#  compensation        :float(24)
#  operational_expense :float(24)
#  total               :float(24)
#  invoice_amount      :float(24)
#  profit              :float(24)
#  month               :integer
#  year                :integer
#

class Employee::EmployeeProfitibilityReport < ActiveRecord::Base
	belongs_to :employee, class_name: "Employee::Employeepersonaldetail", foreign_key: :employee_id

	def self.get_history_report_of(emp_id, month, year)
		where("employee_id = ? and month = ? and year = ?", emp_id, month, year)
	end

  def self.calculate_emp_profitability_report(month, year, dollar_rate)
    @month = month
    @year = year
    @dollar_rate = dollar_rate

    #Delete record if already exists
    where("month = ? AND year = ?", month, year).destroy_all

    #create records for all active employees
    @employees = Employee::Employeepersonaldetail.inactive

    dollar_rate_value = dollar_rate
    dollar_rate_record = ProfDollarRates.find_by_month_and_year(@month, @year)
    dollar_rate_attr = {
    	:month => @month, 
    	:year => @year, 
    	:dollar_rate => @dollar_rate
  	}
    if dollar_rate_record.blank?
      ProfDollarRates.create(dollar_rate_attr)
    else
      dollar_rate_record.update_attributes(dollar_rate_attr)
    end
    
    operational_expense = Variable.find_by_VariableName("OperationalExpense")
    operational_expense_value = operational_expense.blank? ? 0 : (operational_expense.Value.to_i / dollar_rate_value.to_f)
    operational_expense_value = (operational_expense_value.to_f * 100 ).round / 100.0


    @employees.each do |emp|
      payroll = Payroll.find_by_iscomplete("0")

      if payroll.blank?
      	payroll = Payroll.where("idpayroll = (select max(idpayroll) from payrolls )").first
      end
      payroll_detail = Payrolldetail.where("employeeid = ? and idpayroll = ?", emp.EmployeeID, payroll.idpayroll.to_s).first

      unless payroll_detail.blank?
      	term_1 = (payroll_detail.salary + payroll_detail.accruedbonus + payroll_detail.conveyance + payroll_detail.medical + payroll_detail.adjustment + payroll_detail.LeavesEncashmentAmount - payroll_detail.leavewop).to_f
      	compensation = term_1 / dollar_rate_value.to_f
			else
				compensation = 0
			end
      compensation = (compensation.to_f * 100).round / 100.0
      amount = 0
      @invoive_amount = TotalInvoice.select("amount, project_id, percentage_alloc, ishourly, hours, percent_billing, no_of_days")
      															.where("employee_id = ? AND year = ? AND month = ? AND IsSent = 1", emp.EmployeeID, @year, @month)
      if @invoive_amount.present?
        @allocation_percentage = 0
        @billing_percentage = 0
        @total_hours = 0

        @invoive_amount.each do |temp|
        	logger.debug "#{temp.inspect}"
        	temp.no_of_days = 0 if temp.no_of_days.nil?
          @allocation_percentage += temp.percentage_alloc == nil ? 0 : (temp.percentage_alloc / Time.local(@year, @month).to_date.end_of_month.day.to_i) * temp.no_of_days #temp.percentage_alloc

          if temp.ishourly
            @billing_percentage += temp.hours / 170 * 100
            @total_hours += temp.hours
          else
            if temp.percent_billing.present? and temp.no_of_days.present?
              @billing_percentage += temp.percent_billing / Time.local(@year, @month).to_date.end_of_month.day.to_i * temp.no_of_days #temp.percent_billing/31*temp.no_of_days
            end
          end
          currency = ProjectInvoiceNumber.find_by_project_id_and_month_and_year(temp.project_id, @month, @year)
          
          if currency.IsCurrencyDollar == false
            currency = @dollar_rate
          else
            currency = 1
          end

          amount = (amount + temp.amount.to_f) / currency.to_f
        end
      end

      employee_name = "#{emp.FirstName} #{emp.LastName}"

      profit = amount- (compensation + operational_expense_value)
      attributes = {
        :employee_id => emp.EmployeeID,
        :employee_name => employee_name,
        :compensation => compensation,
        :operational_expense => operational_expense_value,
        :total => compensation + operational_expense_value,
        :invoice_amount => amount,
        :profit => profit,
        :month => @month,
        :year => @year
      }

      building = create(attributes)
      logger.debug "Calculating Employee Profitibility Report: -> #{building.inspect}"
    end

    logger.debug "Count: #{Employee::EmployeeProfitibilityReport.count}"
  end
end

app/models/employee/employeebankaccountdetail.rb
# == Schema Information
#
# Table name: employeebankaccountdetails
#
#  EmployeeID    :string(6)        default(""), not null, primary key
#  BankAccountNo :string(45)       default(""), not null
#  BankName      :string(45)       default(""), not null
#  BankBranch    :string(45)       default(""), not null
#

class Employee::Employeebankaccountdetail < ActiveRecord::Base
	belongs_to :employee, class_name: "Employee::Employeepersonaldetail", foreign_key: :EmployeeID, :dependent => :delete

	after_initialize :default_values

	private

	def default_values
    self.BankAccountNo = "0" if self.BankAccountNo.blank?
    self.BankName = "0" if self.BankName.blank?
    self.BankBranch = "0" if self.BankBranch.blank?
  end
end

app/models/employee/employeebenefit.rb
# == Schema Information
#
# Table name: employeebenefits
#
#  MedicalInsuranceType :string(10)       default(""), not null
#  isPickAndDropAvailed :boolean          not null
#  EmployeeID           :string(6)        default(""), not null, primary key
#  ConveyancePolicy     :integer
#  AccrualPercentage    :float(24)
#

class Employee::Employeebenefit < ActiveRecord::Base
	belongs_to :employee, class_name: "Employee::Employeepersonaldetail", foreign_key: :EmployeeID, :dependent => :delete
	
	def default_values
    self.isPickAndDropAvailed ||= 0
  end


  after_initialize :default_values

	private

	def default_values
    self.isPickAndDropAvailed ||= 0
    self.MedicalInsuranceType = "Takaful" if self.MedicalInsuranceType.blank?
    self.ConveyancePolicy = 0 if self.ConveyancePolicy.blank?
  end
end

app/models/employee/employeefamily.rb
# == Schema Information
#
# Table name: employeefamilies
#
#  EmployeeID    :string(6)        default(""), not null, primary key
#  MaritalStatus :string(10)       default(""), not null
#  NoOfChildren  :integer          not null
#

class Employee::Employeefamily < ActiveRecord::Base
	belongs_to :employee, class_name: "Employee::Employeepersonaldetail", foreign_key: :EmployeeID, :dependent => :delete

	after_initialize :default_values

	private

	def default_values
		self.MaritalStatus = "Single" if self.MaritalStatus.blank?
    self.NoOfChildren ||= "0"
  end
end

app/models/employee/employeefamilydetail.rb
# == Schema Information
#
# Table name: employeefamilydetails
#
#  EmployeeID     :string(6)        default(""), not null
#  FamilyDetailID :integer          not null, primary key
#  Name           :string(45)       default(""), not null
#  Relationship   :string(45)       default(""), not null
#  DateOfBirth    :datetime         not null
#

class Employee::Employeefamilydetail < ActiveRecord::Base
	belongs_to :employee, class_name: "Employee::Employeepersonaldetail", foreign_key: :EmployeeID, :dependent => :delete
	scope :for_unregistered_employee, -> (employee_id) { where("EmployeeID = '#{employee_id}'") }

	validates :Name, :Relationship, :DateOfBirth, presence: true
end

app/controllers/employees_controller.rb
class	EmployeesController < ApplicationController
	prepend_before_action :qualification_params, only: [:qualifications]
	prepend_before_action :family_detail_params, only: [:family_details]

	def qualifications
		@unregistered_employee = params[:unregister_emp_id]
		@qualification = Employee::Educationdetail.new(qualification_params)
		@qualification.EmployeeID = @unregistered_employee
		if @qualification.save
			respond_to do |format| 
				@education_details = Employee::Educationdetail.for_unregistered_employee(@unregistered_employee)
				format.js
			end
		else
			render :json => { status: :error, message: @qualification.errors.full_messages.map { |msg| content_tag(:li, msg) }.join }
		end
	end

	def destroy_qualification
		@unregisted_employee_education = Employee::Educationdetail.find_by_EmployeeID(params[:unregister_emp_id])
		@unregisted_employee_education.destroy
		render :json => { status: :error, message: "Education Removed" }
	end

	def family_details
		@unregistered_employee = params[:unregister_emp_id]
		@family_detail = Employee::Employeefamilydetail.new(family_detail_params)
		@family_detail.EmployeeID = @unregistered_employee
		if @family_detail.save
			respond_to do |format| 
				@family_details = Employee::Employeefamilydetail.for_unregistered_employee(@unregistered_employee)
				format.js
			end
		else
			render :json => { status: :error, message: @family_detail.errors.full_messages.map { |msg| content_tag(:li, msg) }.join }
		end
	end

	def destroy_family_detail
		@unregisted_employee_family_detail = Employee::Employeefamilydetail.find_by_EmployeeID(params[:unregister_emp_id])
		@unregisted_employee_family_detail.destroy
		render :json => { status: :error, message: "Family Detail Removed" }
	end

	def create
		@unregistered_employee_id = params[:unregister_emp_id]
		Employee::Employeepersonaldetail.transaction do 
			begin
				# Creating Employee
				@employee = Employee::Employeepersonaldetail.build_employee(employee_params)
				unless @employee.save
					render :json => { status: :error, message: @employee.errors.full_messages.map { |msg| content_tag(:li, msg) }.join } and return
				end

				# Creating Bank Account
				@bank_account_details = @employee.build_bank_account_detail employee_bank_account_params
				# Creating Family
				@employee_family = @employee.build_employee_family employee_family_params
				# Creating Benefits
				@employee_benefit = @employee.build_employee_benefit employee_benefit_params
				# Creating Salary
				@employee_salary = @employee.build_employee_salary employee_salary_params
				
				# Raise If ant of assocation failed
				Employee::Employeepersonaldetail.perform_rollback!(@employee, @bank_account_details, @employee_family, @employee_benefit, @employee_salary)

				#Otherwise
				@bank_account_details.save
				@employee_family.save
				@employee_benefit.save
				@employee_salary.save

				logger.debug "#{@employee.inspect} --- #{@bank_account_details.inspect} --- #{@employee_family.inspect} --- #{@employee_benefit.inspect} --- #{@employee_salary.inspect}"
				render :json => { status: :ok, message: "Employee Created" }

			rescue *[ActiveRecord::StatementInvalid, ActiveRecord::Rollback] => e
				logger.debug "---ERROR: #{e.message}---"
				render :json => { status: :error, message: "Please try to fill the required fields or Contact tech support!" }
				raise ActiveRecord::Rollback, "Call tech support!"
			end
		end
	end

	private

	# Form Params

	def qualification_params
		qualification_params = {
			:Qualification => params[:qualification],
			:Institute => params[:institute],
			:YearFrom => params[:from_date],
			:YearTo => params[:to_date],
			:Type => params[:type]
		}
	end

	def family_detail_params
		family_dob = params[:family_dob].present? ? Date.strptime(params[:family_dob], '%m/%d/%Y') : nil
		family_detail_params = {
			:Name => params[:member_name],
			:Relationship => params[:relationship],
			:DateOfBirth => family_dob
		}
	end

	def employee_bank_account_params
		bank_account_params = {
			:BankAccountNo => params[:bank_account_no],
			:BankName => params[:bank_name],
			:BankBranch => params[:bank_branch],
		}

		bank_account_params
	end

	def employee_salary_params
		emp_salary_params = {
			:GrossSalary => params[:gross_salary]
		}

		emp_salary_params
	end

	def employee_benefit_params
		emp_benefit_params = {
			:MedicalInsuranceType => params[:medical_insurance],
			:ConveyancePolicy => params[:conveyance],
			:AccrualPercentage => params[:accrual_bonus],
		}

		emp_benefit_params
	end

	def employee_family_params
		emp_family_params = {
			:MaritalStatus => params[:marital_status],
			:NoOfChildren => params[:children]
		}

		emp_family_params
	end

	def employee_params
		emp_dob = params[:date_of_birth].present? ? Date.strptime(params[:date_of_birth], '%m/%d/%Y') : nil
		emp_joining_date = params[:joining_date].present? ? Date.strptime(params[:joining_date], '%m/%d/%Y') : nil
		emp_params = {
			:FirstName => params[:first_name],
			:LastName => params[:last_name],
			:Address => params[:address],
			:HomePhoneNo => params[:home_phone],
			:CellPhoneNo => params[:cell_phone],
			:DateOfBirth =>	emp_dob,
			:Type => params[:ins_type],
			:HomeEmail => params[:personal_email],
			:OfficeEmail => params[:office_email],
			:DateOfJoining => emp_joining_date,
			:NTNNo => params[:ntn_no],
			:NICNo => params[:nic],
			:IsInternee => params[:is_internee],
			:Designation => params[:designation],
			:Gender => params[:gender],
			:unregister_emp_id => @unregistered_employee_id
		}

		emp_params
	end
end

app/helpers/employees_helper.rb
module EmployeesHelper
	Gender = [
		{:gender_id => "0", :gender_name => "Male"},
		{:gender_id => "1", :gender_name => "Female"}
	]
	MaritalStatus = ["Single", "Married"]
	Conveyance = [
		{:conveyance_id => "1", :conveyance_name => "standard"},
		{:conveyance_id => "2", :conveyance_name => "van_service"},
		{:conveyance_id => "3", :conveyance_name => "parking"},
		{:conveyance_id => "4", :conveyance_name => "pick_and_drop"},
		{:conveyance_id => "5", :conveyance_name => "no_conveyance"},
	]
	MedicalInsurance = ["takaful", "alianz"]
end

app/views/employees/shared/_account_info.html.erb
<div class="form-group">
	<%= label_tag :ntn_no, "NTN #" %>
	<%= text_field_tag :ntn_no, params[:ntn_no], placeholder: "NTN No" %>
</div>
<div class="form-group">
	<%= label_tag :bank_account_no %>
	<%= text_field_tag :bank_account_no, params[:bank_account_no], placeholder: "Bank Account No" %>
</div>
<div class="form-group">
	<%= label_tag :bank_name %>
	<%= text_field_tag :bank_name, params[:bank_name], placeholder: "Bank Name" %>
</div>
<div class="form-group">
	<%= label_tag :bank_branch %>
	<%= text_field_tag :bank_branch, params[:bank_branch], placeholder: "Branch" %>
</div>
<div class="form-group">
	<%= label_tag "Medical Insurance" %>
	<%= select_tag :medical_insurance, options_for_select(EmployeesHelper::MedicalInsurance.map{|m| m.split("_").map{|medical| medical.capitalize }.join(" ")}), prompt: "--Select Medical Insurance--" %>
</div>
<div class="form-group">
	<%= label_tag :accrual_bonus %>
	<%= text_field_tag :accrual_bonus, params[:accrual_bonus], placeholder: "Accrual Bonus" %>
</div>

app/views/employees/shared/_basic_info.html.erb
<div class="form-group">
	<%= label_tag :first_name %>
	<%= text_field_tag :first_name, params[:first_name], placeholder: "First Name" %>
</div>
<div class="form-group">
	<%= label_tag :last_name %>
	<%= text_field_tag :last_name, params[:last_name], placeholder: "Last Name" %>
</div>
<div class="form-group">
	<%= label_tag :gender %>
	<%= select_tag :gender, options_for_select(EmployeesHelper::Gender.map{|m| [m[:gender_name], m[:gender_id]]}), prompt: "--Select Gender--" %>
</div>
<div class="form-group">
	<%= label_tag :date_of_birth %>
	<%= text_field_tag :date_of_birth, params[:date_of_birth], id: "employee_dob", placeholder: "MM/DD/YYYY" %>
</div>
<div class="form-group">
	<%= label_tag :marital_status %>
	<%= select_tag :marital_status, options_for_select(EmployeesHelper::MaritalStatus.map{|m| m.capitalize}), prompt: "--Select Marital Status--", onchange: "EmployeeFormDetail.checkMaritalStatus(this);" %>
</div>
<div class="form-group children_for_married_employee">
	<%= label_tag :children %>
	<%= text_field_tag :children, params[:children], placeholder: "No of Children" %>
</div>

app/views/employees/shared/_contact_info.html.erb
<div class="form-group">
	<%= label_tag :nic, "NIC" %>
	<%= text_field_tag :nic, params[:nic], placeholder: "99999-9999999-9" %>
</div>
<div class="form-group">
	<%= label_tag :home_phone %>
	<%= text_field_tag :home_phone, params[:home_phone], placeholder: "Home Number" %>
</div>
<div class="form-group">
	<%= label_tag :cell_phone %>
	<%= text_field_tag :cell_phone, params[:cell_phone], placeholder: "Cell Phone Number" %>
</div>
<div class="form-group">
	<%= label_tag :personal_email %>
	<%= text_field_tag :personal_email, params[:personal_email], placeholder: "Personal Email" %>
</div>
<div class="form-group">
	<%= label_tag :office_email %>
	<%= text_field_tag :office_email, params[:office_email], placeholder: "Office Email" %>
</div>
<div class="form-group">
	<%= label_tag :address %>
	<%= text_area_tag :address, params[:address], placeholder: "Address" %>
</div>

app/views/employees/shared/_employee_info.html.erb
<div class="form-group">
	<%= label_tag :joining_date %>
	<%= text_field_tag :joining_date, params[:joining_date], id: "emp_joining_date", placeholder: "MM/DD/YYYY" %>
</div>
<div class="form-group">
	<br />
	<div class="checkbox">
    <%= check_box_tag :is_internee, params[:is_internee], false, { :class => "styled" } %>
    <label>
      Is Internee
    </label>
  </div>
</div>
<div class="form-group">
	<%= label_tag :designation %>
	<%= select_tag :emp_designation, options_for_select(Designation.all.map{|m| [m.designation, m.designation_id]}), prompt: "--Select Designation--" %>
</div>
<div class="form-group">
	<%= label_tag :conveyance %>
	<%= select_tag :conveyance, options_for_select(EmployeesHelper::Conveyance.map{|m| [m[:conveyance_name].split("_").map{|conveyance| conveyance.capitalize }.join(" "), m[:conveyance_id]]}), prompt: "--Select Conveyance--" %>
</div>
<div class="form-group">
	<%= label_tag :gross_salary %>
	<%= text_field_tag :gross_salary, params[:gross_salary], placeholder: "Salary" %>
</div>

app/views/employees/shared/_form_inputs.html.erb
<%= form_tag employees_path(unregister_emp_id: @employee_id, format: :json), method: :post, id: "new_employee_form" do %>
	<div class="row">
		<div class="col-md-3">
			<fieldset>
				<legend>Basic Info</legend>
				<%= render "employees/shared/basic_info" %>
			</fieldset>
		</div>
		<div class="col-md-3">
			<fieldset>
				<legend>Contact Info</legend>
			</fieldset>
			<%= render "employees/shared/contact_info" %>
		</div>
		<div class="col-md-3">
			<fieldset>
				<legend>Employee Info</legend>
			</fieldset>
			<%= render "employees/shared/employee_info" %>
		</div>
		<div class="col-md-3">
			<fieldset>
				<legend>Account Info</legend>
			</fieldset>
			<%= render "employees/shared/account_info" %>
		</div>
	</div>
<% end %>
<hr />
<blockquote>
	<h3>Add Employee Details</h3>
</blockquote>
<ul class="nav nav-tabs" role="tablist">
  <li role="presentation" class="active"><a href="#emp_qualification_tab" aria-controls="home" role="tab" data-toggle="tab"><strong>Qualification</strong></a></li>
  <li role="presentation"><a href="#emp_family_tab" aria-controls="profile" role="tab" data-toggle="tab"><strong>Family Details</strong></a></li>
</ul>
<br />
<div class="tab-content">
  <div role="tabpanel" class="tab-pane active fade in" id="emp_qualification_tab">
		<div class="qualification_records">
			<%= render "/employees/qualifications_fields" %>
		</div>
		<!-- Education Details Form -->
		<%= form_tag qualifications_employees_path(unregister_emp_id: @employee_id, format: :js), method: :post, id: "employee_qualification_form" do %>
			<div class="row">
				<div class="col-md-8">
					<div class="form-group">
						<label>Qualification</label>
						<%= text_area_tag :qualification, params[:qualification], rows: 5, placeholder: "Qualification" %>
					</div>
				</div>
				<div class="col-md-4">
					<div class="form-group">
						<label>From Date</label>
						<%= text_field_tag :from_date, params[:from_date], placeholder: "From Year", class: "from_date" %>
					</div>
					<div class="form-group">
						<label>To Date</label>
						<%= text_field_tag :to_date, params[:to_date], placeholder: "To Year", class: "to_date" %>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-6">
					<label>Institute</label>
					<%= text_field_tag :institute, params[:institute], placeholder: "Institute" %>
				</div>
				<div class="col-md-6">
					<label>Type</label>
					<%= text_field_tag :type, params[:type], placeholder: "Type" %>
				</div>
			</div>
			<br />
			<div class="row">
				<div class="col-md-6 pull-right">
					<div class="form-group">
						<%= button_tag "Save", type: "button", class: "btn btn-primary pull-right", onclick: "Employee.submitQualificationForm(this);" %>
					</div>
				</div>
			</div>
		<% end %>
  </div>

  <div role="tabpanel" class="tab-pane" id="emp_family_tab">
		<div class="family_details_records">
			<%= render "/employees/family_details_fields" %>
		</div>

		<!-- Family Details Form -->
		<%= form_tag family_details_employees_path(unregister_emp_id: @employee_id, format: :js), method: :post, id: "employee_family_details_form" do %>
			<div class="row">
				<div class="col-md-4">
					<div class="form-group">
						<%= label_tag :member_name %>
						<%= text_field_tag :member_name, params[:member_name], placeholder: "Memeber Name" %>
					</div>
				</div>
				<div class="col-md-4">
					<div class="form-group">
						<%= label_tag :relationship %>
						<%= text_field_tag :relationship, params[:relationship], placeholder: "Relationship" %>
					</div>
				</div>
				<div class="col-md-4">
					<div class="form-group">
						<%= label_tag :family_dob %>
						<%= text_field_tag :family_dob, params[:family_dob], placeholder: "Date of Birth", class: "family_dob" %>
					</div>
				</div>
			</div>
			<br />
			<div class="row">
				<div class="col-md-6 pull-right">
					<div class="form-group">
						<%= button_tag "Save", type: "button", class: "btn btn-primary pull-right", onclick: "Employee.submitFamilyDetailForm(this);" %>
					</div>
				</div>
			</div>
		<% end %>
  </div>
</div>