config/routes.rb
Rails.application.routes.draw do
  resources :invoices, only: [:index, :update] do
    collection do
      get "invoice_number" => "invoices#get_invoice_number"
      get "synchronisation_of_invoices" => "invoices#synchronisation_of_invoices"
      post "fetch_invoices" => "invoices#fetch_invoices"
      post "custom_invoice" => "invoices#custom_invoice"
      get "new_employee" => "invoices#unregistered_employee"
      get "resync_status" => "invoices#resync_status"
      post "generate_invoices" => "invoices#generate_invoices", :as => :generate
      put "/recalculate" => "invoices#recalculate"
      get "/status", to: "invoices#invoice_status"
    end
  end

  match "invoices/:invoice_created_date" => "invoices#show", via: [:get, :pdf], :as => :invoice_pdf

  resources :employees, :only => [:create] do 
    collection do 
      post "/qualifications/:unregister_emp_id" => "employees#qualifications", as: :qualifications
      post "/family_details/:unregister_emp_id" => "employees#family_details", as: :family_details
      delete "/destroy_qualification/:unregister_emp_id" => "employees#destroy_qualification", as: :remove_qualification
      delete "/destroy_family_detail/:unregister_emp_id" => "employees#destroy_family_detail", as: :remove_family_detail
    end
  end

  namespace :reports do
    get "/" => "base#listing"
    resources :profitability_reports, only: [:index] do
      collection do 
        get "/divisions" => "profitability_reports#divisions_report", as: :divisions
        get "/projects" => "profitability_reports#projects_report", as: :projects
        get "/project" => "profitability_reports#specified_project_report", as: :project
        get "/division_based" => "profitability_reports#specified_division_report", as: :division_based
        get "/designations" => "profitability_reports#designations_report", as: :designations
        get "/employee_history" => "profitability_reports#employee_history_report", as: :employee_history
      end
    end
    resources :re_calculate_reports, only: [:index] do
      collection do 
        post "/calculate_profitability_reports" => "re_calculate_reports#calculate_profitability_reports"
      end
    end
  end

  resources :rates, only: [:index, :create, :update] do
    get "/sync_designations" => "rates#sync_designations", on: :collection
    get "/:designation_id/designation_rate_history" => "rates#designation_rate_history", on: :collection
  end

  resources :projects, only: [:index] do
    get "/sync_projects" => "projects#sync_projects", on: :collection
  end

  devise_for :users
  devise_scope :user do
    get "settings", to: "devise/registrations#edit"
  end

  get 'home/welcome'

  authenticated :user do
    root 'invoices#index', as: :authenticated_root
  end

  unauthenticated :user do
    devise_scope :user do 
      get "/", to: "devise/sessions#new"
    end
  end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
	PaymentTerms = ["Net 10 Days", "Net 15 Days", "Net 20 Days", "Net 30 Days", "Net 45 Days", "Net 60 Days", "Immediate"]
	Currency = ["PKR", "US$"]
	
	def invoice_hours(invoice)
		"invoice_hours" if invoice.ishourly
	end

	def hourly_or_non_hourly(generated_invoice)
		return "---" if generated_invoice[:hours].blank? and generated_invoice[:percent_billing].blank?

		if generated_invoice[:ishourly] == true
			pluralize(generated_invoice[:hours], 'hr')
		else
			"#{generated_invoice[:percent_billing]} %"
		end
	end

	def generated_invoice_rates(generated_invoice)
		return "---" if generated_invoice[:hours].blank? and generated_invoice[:percent_billing].blank?

		if generated_invoice[:ishourly] == true
			rate_type = "hour"
		else
			rate_type = "month"
		end
		
		"#{generated_invoice[:rates]} / #{rate_type}"
	end

	def invoice_description(generated_invoice)
		html = ""
		html += "<strong>#{generated_invoice[:description][:full_name]} - #{generated_invoice[:description][:designation]}</strong>"
		html += " - #{generated_invoice[:description][:task_notes]}" if generated_invoice[:description][:task_notes].present?
		html += "<br />"
		html += "#{generated_invoice[:description][:duration].blank? ? "---" : generated_invoice[:description][:duration]}"

		html.html_safe
	end

	def currency_label(currency)
		if currency == false
			"PKR"
		else
			"US$"
		end
	end


	def invoice_result(invoice, status)
		case status
		when "fetch".to_sym
			if invoice.is_fetched? == "fetched".to_sym 
				invoice.project_name
			else 
				"---"
			end
		when "processed".to_sym
			if invoice.is_processed? == "processed".to_sym 
				invoice.project_name
			else 
				"---"
			end
		when "unprocessed".to_sym
			if invoice.is_unprocessed? == "unprocessed".to_sym 
				invoice.project_name
			else 
				"---"
			end
		end
	end

	def fetched_invoice(invoice)
		if invoice.is_fetched? == "fetched".to_sym 
			invoice.project_name
		else 
			"---"
		end
	end

	def fetched_invoice(invoice)
		if invoice.is_fetched? == "fetched".to_sym 
			invoice.project_name
		else 
			"---"
		end
	end

	def editable_for(field_name, invoice, count = "")

		if invoice.IsAdjustment == false and invoice.IsShadow == true
			@title = "This Record is not editable"
		else
			@title = "Click To Edit"
			if field_name == "hours".to_sym
				if invoice.ishourly == true
					@title = "Click To Edit"
				else
					@title = "This is a non hourly employee"
				end
			end
		end

		link_to "javascript:void(0);", onkeydown: "activateOnEnterKey(event);", onclick: "isShadowCompatibility(this, #{invoice.attributes.to_json});", style: "text-decoration: none;", data: { toggle: "tooltip", placement: "top" }, title: @title do

			case field_name
			when "rates".to_sym
				if invoice.IsAdjustment == false and invoice.IsShadow == true
					"#{invoice.rates}"
				else
					best_in_place invoice, :rates, :as => :input, :path => invoice_path(invoice.id), 
																:inner_class => "form-control", placeholder: "---", html_attrs: { onchange: "updateAmount(this, 'rates', #{count});" }
				end
			when "unpaid_leaves".to_sym
				if invoice.IsAdjustment == false and invoice.IsShadow == true
					"#{invoice.unpaid_leaves}"
				else
					best_in_place invoice, :unpaid_leaves, :as => :input, :path => invoice_path(invoice.id), 
																:inner_class => "form-control", placeholder: "---", html_attrs: { onchange: "updateAmount(this, 'unpaid_leaves', #{count});" }
				end
			when "amount".to_sym
				if invoice.IsAdjustment == false and invoice.IsShadow == true
					"#{invoice.amount}"
				else
					best_in_place invoice, :amount, :as => :input, :path => invoice_path(invoice.id), 
																:inner_class => "form-control", placeholder: "---", html_attrs: { onchange: "calculateTotalData(this, 'amount'); updateRates(this, #{count});" }
        end
			when "reminder".to_sym
				if invoice.IsAdjustment == false and invoice.IsShadow == true
					invoice.reminder.present? ? "#{invoice.reminder}" : "---"
				else
					best_in_place invoice, :reminder, :as => :input, :path => invoice_path(invoice.id), 
																:inner_class => "form-control", placeholder: "---"
				end
			when "hours".to_sym
				if invoice.IsAdjustment == false and invoice.IsShadow == true
					invoice.hours.present? ? "#{invoice.hours}" : "---"
				else
					if invoice.ishourly
						best_in_place invoice, :hours, :as => :input, :path => invoice_path(invoice.id), 
																		:inner_class => "form-control", placeholder: "---", html_attrs: { onchange: "calculateTotalData(this, 'hours'); updateAmount(this, 'hours', #{count});" }
					else
						"---"
					end
				end
			when "billing".to_sym
				if invoice.IsAdjustment == false and invoice.IsShadow == true
					"#{invoice.percent_billing}"
				else
					best_in_place invoice, :percent_billing, :as => :input, :path => invoice_path(invoice.id), 
																		:inner_class => "form-control", placeholder: "---"
				end
			when "worked_days".to_sym
				if invoice.IsAdjustment == false and invoice.IsShadow == true
					"#{invoice.no_of_days}"
				else
					best_in_place invoice, :no_of_days, :as => :input, :path => invoice_path(invoice.id), 
																		:inner_class => "form-control", placeholder: "---", html_attrs: { onchange: "updateAmount(this, 'no_of_days', #{count});" }
				end
			when "description".to_sym
				if invoice.IsAdjustment == false and invoice.IsShadow == true
					"#{invoice.description}"
				else
					ok_button = "<i class=\"fa fa-check\"></i>".html_safe
					best_in_place invoice, :description, :as => :textarea, :path => invoice_path(invoice.id), 
																	html_attrs: {:placeholder => "Description"}, 
																	:inner_class => "form-control",
																	placeholder: "---"

																	# ok_button: "Save", 
																	# :ok_button_class => "btn btn-success btn-sm d_btn", 
																	# :cancel_button => "Cancel", 
																	# :cancel_button_class => "btn btn-sm btn-danger d_btn",
				end
			end
		end
	end
end

app/views/invoices/_fetching_invoices.html.erb
<% if @current_invoices.present? %>
	<div class="row">
		<div class="col-md-6">
			<blockquote>
				<h3><strong><%= @project_name %></strong></h3>
			</blockquote>
		</div>
		<div class="col-md-6">
			<blockquote class="blockquote-reverse">
				<h3>
					<div class="btn-group">
					  <a href="#" class="btn btn-default">History of Generated Invoices</a>
					  <a href="#" class="btn btn-default dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></a>
					  <ul class="dropdown-menu scrollable-dropdown">
					  	<% if @invoices_generated_dates.present? %>
						  	<% @invoices_generated_dates.each_with_index do |date, index| %>
						    	<li>
						    		<% index += 1 %>
						    		<% created_date = I18n.l date.createdon, format: :invoices_datetime %>
					    			<%= link_to invoice_pdf_path(created_date.to_s.split(" ").join("_")), target: "_blank" do %>
					    				<%= I18n.l(date.createdon, format: :invoices_generated) %>
					    				&nbsp;
					    				<% if date.IsSent == true %>
							    			<label class="label label-success">Sent to Customer</label>
						    			<% end %>
					    			<% end %>
					    		</li>
					    		<% unless index == @invoices_generated_dates.length %>
					    			<li class="divider"></li>
				    			<% end %>
					    	<% end %>
				    	<% else %>
				    		<li><a href="#">There are invoice generated</a></li>
				    	<% end %>
					  </ul>
					</div>
				</h3>
			</blockquote>
		</div>
	</div>
	<% if @is_unregistered_employee == true %>
		<div class="row">
			<div class="col-md-6">
				<div class="list-group">
				  <a href="javascript:void(0);" class="list-group-item">
				    <h4 class="list-group-item-heading">
				    	<blockquote>Records for these Employees are not found in FOMS</blockquote>
			    	</h4>
				    <ul class="list-group">
				    	<% @unregistered_employees.each_with_index do |employee, count| %>
				    		<% count += 1 %>
							  <li class="list-group-item">
							    <label class="label label-primary pull-right" id="new_employee" onclick="EmployeeFormDetail.openEmployeeForm(this);" method="get" action="<%= new_employee_invoices_path(format: :js) %>" data-employee-index="<%= count %>" data-toggle="tooltip" data-project-id="<%= @project_id %>" data-month="<%= @month %>" data-year="<%= @year %>" data-employee-id="<%= employee.employee_id %>" data-placement="left" title="Add This Employee">Add</label>
							    <strong><%= employee.employee_name %></strong>
							  </li>
						  <% end %>
						</ul>
				  </a>
				</div>
			</div>
		</div>
	<% end %>
	<div class="row">
		<div class="col-md-10">
			<%= form_tag invoice_pdf_path(:invoice_created_date => ""), method: :get, target: "_blank", id: "invoices_pdf_generate_form" do %>
				<div class="row">
					<div class="col-md-3">
						<label>Currency</label>
						<%= select_tag :pkr_and_dollar, options_for_select(InvoicesHelper::Currency.map{|m| m}), class: "form-control", onchange: "getCurrencyLabel(this);" %>
					</div>
					<div class="col-md-3">
						<label>Payment Terms</label>
						<%= select_tag :payment_terms, options_for_select(InvoicesHelper::PaymentTerms.map{|m| m}), class: "form-control" %>
					</div>
					<div class="col-md-3">
						<div class="form-group">
							<label>Invoice Date</label>
							<%= text_field :invoice_sent_date, params[:invoice_sent_date], class: "form-control", value: (l Date.today, format: :short_date), id: "invoice_date" %>
							<span class="invoice_error" style="display:none;"></span>
						</div>
					</div>
					<div class="col-md-3">
						<div class="form-group">
							<label>Invoice Number</label>
							<%= text_field :invoice_no, params[:invoice_no], class: "form-control", id: "invoice_no", placeholder: "Invoice Number" %>
							<span class="invoice_error" style="display:none;"></span>
						</div>
					</div>
				</div>
			<% end %>
		</div>
		<div class="col-md-2">
			<%= link_to "Generate Invoice", "javascript:void(0);", target: "_blank", class: "btn btn-info", style: "margin-top: 23px;", id: "generate_invoices", data: { action: generate_invoices_path(format: :json), :method => :post } %>
		</div>
	</div>
	<br />
	<div class="table-responsive">
		<span id="count_index_invoice" data-count-index="<%= @current_invoices.length %>"></span>
		<table class="table table-striped table-hover" id="invoices_table">
			<thead>
				<tr>
					<th></th>
					<th>Hours</th>
					<th>% Alloc</th>
					<th>$ Billing</th>
					<th>No of Days Worked</th>
					<th>Description</th>
					<th>
						Rates <span class="currency_label"><%= currency_label(@currency) %></span>
					</th>
					<th>Unpaid Leaves</th>
					<th>
						Amount <span class="currency_label"><%= currency_label(@currency) %></span>
					</th>
					<th>Reminder</th>
				</tr>
			</thead>
			<tbody>
				<% @current_invoices.each_with_index do |invoice, count| %>
					<% count += 1 %>
					<tr class="id_params_<%= count %>" data-invoice-id="<%= invoice.id %>">
						<%= hidden_field_tag :is_hourly, invoice.ishourly, class: "is_hourly_params_#{count}" %>
						<td></td>
						<td class="<%= invoice_hours(invoice) %> hours_params_<%= count %>">
							<%= editable_for(:hours, invoice, count) %>
						</td>
						<td>
							<%= invoice.percentage_alloc %>
						</td>
						<td class="percent_billing_params_<%= count %>">
							<%= editable_for(:billing, invoice) %>
						</td>
						<td class="worked_days_<%= count %>">
							<%= editable_for(:worked_days, invoice, count) %>
						</td>
						<td class="description_params_<%= count %>">
							<%= editable_for(:description, invoice) %>
						</td>
						<td class="rates_params_<%= count %>">
							<%= editable_for(:rates, invoice, count) %>
						</td>
						<td class="unpaid_leaves_<%= count %>">
							<%= editable_for(:unpaid_leaves, invoice, count) %>
						</td>
						<td class="invoice_amount amount_params_<%= count %>">
							<%= editable_for(:amount, invoice, count) %>
						</td>
						<td>
							<%= editable_for(:reminder, invoice) %>
						</td>
					</tr>
				<% end %>
				<tr id="add_new_invoice">
					<td>
						<%= link_to "#", class: "text-warning", data: { toggle: "tooltip", placement: "top" }, title: "Add Custom Invoice", id: "add_inline_invoice_btn" do %> 
							<i class="fa fa-plus-square-o fa-2x"></i> 
						<% end %>
					</td>
					<td colspan="9"></td>
				</tr>
				<tr class="for_total">
					<th>Total</th>
					<th id="invoice_total_hours"><%= @total_hours %></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th id="invoice_total_amount"><%= @total_amount %></th>
					<th></th>
				</tr>
			</tbody>
		</table>
	</div>
<% else %>
	<div class="alert alert-info">
		<blockquote style="margin:0;"><strong>No Record Present</strong></blockquote>
	</div>
<% end %>

app/views/invoices/fetch_invoices.js.erb
$("#fetched_invoices").hide().html("<%= escape_javascript(render 'fetching_invoices').html_safe %>").fadeIn(500);

$(".best_in_place").best_in_place()
$('[data-toggle="tooltip"]').tooltip()



$("#invoice_date").datepicker({
  format: 'M d, yyyy',
  orientation: 'bottom left'
}).on('changeDate', function(e) {
  return $(this).datepicker('hide');
});


// $table = $("#invoices_table tbody");
// $rows = $table.find("tr")

// $.each($rows, function() {
// 	$(this).find("td").each(function(){
// 		if($(this).find("a").length) {
// 			$(this).find("a").addClass("editable");
// 		} else {
// 			$(this).addClass("editable");
// 		}
// 	});
// });

// var tab_count = 0;
// $.each($rows, function(){
// 	var elem;
// 	elem = $(this).find(".editable")
// 	elem.each(function(){
// 		$(this).attr("tabindex", tab_count += 1)
// 	});
// });





// $.fn.editable.defaults.mode = 'popup';
// $.fn.editable.defaults.ajaxOptions = {type: "PUT"};
// $('#percent_allocation').editable();

app/views/invoices/index.html.erb
<div id="generate_invoices_board">
	<blockquote class="page-heading">
		<p>Generate <small>New Invoices</small></p>
	</blockquote>

	<div class="panel panel-info" id="panel-invoices">
	  <div class="panel-heading">
	  	<div class="row">
	  		<div class="col-md-6 col-xs-8">
	  			<h3 class="panel-title">
			    	<i class="fa fa-external-link"></i> <strong>Synchronize Data</strong> 
			  	</h3>
	  		</div>
	  		<div class="col-md-6 col-xs-4">
	  		</div>
	  	</div>
	  </div>
		<div class="panel-body">
			<div class="row">
				<div class="col-md-3">
					<blockquote>
			  		<label class="invoice_label">View Invoices For The Month Of:</label>
	  				<%= text_field_tag :month_year, params[:month_year], id: "invoice_month_year", class: "form-control invoice_input", placeholder: "Select Date" %>
			  	</blockquote>
				</div>
				<div class="col-md-3">
					<blockquote>
					  <label class="invoice_label">Total No Of Days:</label>
					  <div class="invoice_input">
					  	<%= text_field_tag :no_of_days, params[:no_of_days], class: "form-control", data: { invoice_no_url: invoice_number_invoices_path(format: :json) }, onblur: "recalculateAmount(this);" %>
				  	</div>
					  <div class="alert alert-danger" id="total_no_days_alert" style="display:none;">
					  	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
					  	No of Days Changed All amounts are Recalculated
					  </div>
					</blockquote>
				</div>
				<div class="col-md-3">
					<blockquote>
				  	<input type="checkbox" name="invoice_project">
				  	<br />
				  	<div id="invoice_projects_select">
				  		<%= select_tag :invoice_projects, options_for_select(@projects.map{|m| [m.name, m.id]}), class: "form-control", prompt: "--Select Project--" %>	
				  	</div>
					</blockquote>
				</div>
				<div class="col-md-3">
					<blockquote>
				  	<input type="checkbox" name="invoice_employee">
				  	<br />
				  	<div id="invoice_employees_select">
			  			<%= select_tag :invoice_employees, options_for_select(@employees.map{|m| [m.full_name, m.EmployeeID]}), class: "form-control", prompt: "--Select Employee--" %>
						</div>
					</blockquote>
				</div>
			</div>
			<div class="row">
				<div class="col-md-2">
					<%= button_tag :class => 'btn btn-danger btn-block', id: "fetch_invoices_btn", "data-action" => fetch_invoices_invoices_path, "data-method" => "post" do %>
						<i class="fa fa-search"></i> Get Invoices
					<% end %>
				</div>
				<div class="col-md-8">
					<%= link_to "javascript:void(0);", class: "btn btn-default btn-block", onclick: "syncInvoices(this, 'Synchronise Invoices');", data: { action: synchronisation_of_invoices_invoices_path(format: :json), method: "Get", isProject: false } do %>
						<i class="glyphicon glyphicon-link"></i> Sync All Invoices
					<% end %>
				</div>
				<div class="col-md-2">
					<%= link_to "javascript:void(0);", class: "btn btn-primary pull-right btn-block", onclick: "syncInvoices(this, 'Synchronise Invoice');", data: { action: synchronisation_of_invoices_invoices_path(format: :json), method: "Get", isProject: true } do %>
						<i class="glyphicon glyphicon-link"></i> Sync Data
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="invoices_display">
	<div class="row">
		<div class="col-md-12">
			<div id="fetched_invoices">
				<%= render "fetching_invoices" %>
			</div>
		</div>
	</div>
</div>

<div id="employee_form"></div>

app/views/invoices/invoice_status.html.erb
<blockquote class="page-heading">
	<p>Invoice Status</p>
</blockquote>

<% if @invoices.present? %>
	<div class="table-scrollable">
		<table class="table table-striped">
			<thead>
				<tr>
					<td align="middle">S.No</td>
		      <td align="middle">ID</th>
		      <td align="middle">Fetched</td>
		      <td align="middle">Processed</td>
		      <td align="middle">Unprocessed</td>
		      <td align="middle">Month</td>
		      <td align="middle">Year</td>
				</tr>
			</thead>
			<tbody>
				<% count = ((params[:page] || 1).to_i - 1) * 20 %>
		    <% @invoices.each_with_index do |invoice, i| %>
		      <tr>
		        <td align="middle"><%= (i +  1) + count %></td>
		        <td align="middle"><%= invoice.project_id %></td>
		        <td align="middle"><%= invoice_result(invoice, :fetch) %></td>
		        <td align="middle" class="<%= invoice.is_processed? == :processed ? 'success' : '' %>"><%= invoice_result(invoice, :processed) %></td>
		        <td align="middle" class="<%= invoice.is_unprocessed? == :unprocessed ? 'danger' : '' %>"><%= invoice_result(invoice, :unprocessed) %></td>
		        <td align="middle"><%= I18n.t("date.abbr_month_names")[invoice.month.to_i] %></td>
		        <td align="middle"><%= invoice.year %></td>
		      </tr>
		    <% end %>
			</tbody>
		</table>
	</div>
	<%= will_paginate @invoices, renderer: BootstrapPagination::Rails %>
<% else %>
	<div class="alert alert-danger">
		No Invoices are present for <strong><%= "#{I18n.t("date.abbr_month_names")[@month.to_i]}, #{@year}" %></strong>
	</div>
<% end %>

app/views/invoices/show.html.erb
<%= content_for :title, "Invoice" %>
<%= content_for :header, "false" %>
<%= content_for :footer, "false" %>
<style type="text/css">
	body { padding: 15px 0px; !important; }
</style>
<div class="container">
	<div class="header">
		<%= image_tag "folio3-logo.png" %>
		<div class="bottom"></div>
	</div>
	<div class="content">
		<div class="row">
			<div class="col-md-6">
				<blockquote>
					<p>Folio3 Software Inc., c/o Kathy Chao, C. G. Uhlenberg LLP, 333 Twin Dolphin Drive, Suite 230, Redwood CIty, CA 94065</p>
				</blockquote>
			</div>
			<div class="col-md-6">
				<blockquote class="blockquote-reverse">
					<%= link_to invoice_pdf_path(invoice_no: @invoice_no.split(" "), invoice_sent_date: @invoice_date.to_s.split(" "), payment_terms: @payment_terms, currency: @currency, format: :pdf), method: :get, class: "btn btn-success" do %>
						Download PDF <i class="fa fa-file-pdf-o"></i>
					<% end %>
				</blockquote>
			</div>
		</div>
		<div class="invoice_info">
			<div class="row">
				<div class="col-md-6">
					<blockquote class="project_name">
						<%= @project.name %>
					</blockquote>
				</div>
				<div class="col-md-6 pull-right">
					<div class="alert alert-info">
						<span class="heading">Customer Info:</span>
						<ul class="list-names">
							<li><strong>Customer Name:</strong> <%= @customer_name %></li>
							<li><strong>Customer Address:</strong> <%= @customer_address %></li>
							<li><strong>Customer Email:</strong> <%= @customer_email %></li>
						</ul>
						<span class="heading">Invoice Info:</span>
						<ul class="list-names">
							<li><strong>Invoice No:</strong> <%= @invoice_no %></li>
							<li><strong>Invoice Date:</strong> <%= l @invoice_date, format: :short_date %></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
		<div id="total_invoices_for_customer">
			<%= render "invoices/shared/pdf_invoices" %>
			<%#= @processed_invoices.count %>
			<%#= @total_invoices.count %>
		</div>
	</div>
	<div class="footer">
		<div class="row">
			<div class="col-md-6">
				<p><strong>Payment Terms</strong></p>
				<p><%= @payment_terms %></p>
				<p><strong>Wire Transfer Instructions:</strong></p>
				<p>Remit US Dollars to Folio3 Software Inc account number 16629-66005 at Bank of America, routing number 121000358.</p>
				<p><strong>Check Payment:</strong></p>
				<p>Alternatively, send a check to our US Address: 
					<strong>Folio3, c/o Kathy Chao, C. G. Uhlenberg LLP, 333 Twin Dolphin Drive, Suite 230, Redwood City, CA 94065.</strong></p>
			</div>
		</div>
		<div class="bottom"></div>
		<div class="row">
			<div class="col-md-12">
				<div style="text-align:center;font-weight:bold;">Invoice Generated On <%= @invoice_created_date %></div>
			</div>
		</div>
	</div>
</div>

app/views/invoices/show.pdf.erb
<div class="content">
	<div class="bottom"></div>
	<p>
    Folio3 Software Inc., c/o Kathy Chao, C. G. Uhlenberg LLP, 333 Twin Dolphin Drive, Suite 230, Redwood CIty, CA  94065
  </p>
	<div class="invoice_info">
		<div class="project_name_for_pdf">
			<%= @project.name %>
		</div>
		<br />
		<span class="heading">Customer Info:</span>
		<ul class="list-names">
			<li><strong>Customer Name:</strong> <%= @customer_name %></li>
			<li><strong>Customer Address:</strong> <%= @customer_address %></li>
			<li><strong>Customer Email:</strong> <%= @customer_email %></li>
		</ul>
		<span class="heading">Invoice Info:</span>
		<ul class="list-names">
			<li><strong>Invoice No:</strong> <%= @invoice_no %></li>
			<li><strong>Invoice Date:</strong> <%= l @invoice_date, format: :short_date %></li>
		</ul>
	</div>
	</div>
	<div id="total_invoices_for_customer_pdf">
		<%= render "invoices/shared/pdf_invoices.html.erb" %>
	</div>
</div>
<br />
<div class="footer">
	<div class="row">
		<div class="col-md-6">
			<p><strong>Payment Terms</strong>
			<br /><%= @payment_terms %></p>
			<p><strong>Wire Transfer Instructions:</strong>
			<br />Remit US Dollars to Folio3 Software Inc account number 16629-66005 at Bank of America, routing number 121000358.</p>
			<p><strong>Check Payment:</strong>
			<br />Alternatively, send a check to our US Address: 
				<strong>Folio3, c/o Kathy Chao, C. G. Uhlenberg LLP, 333 Twin Dolphin Drive, Suite 230, Redwood City, CA 94065.</strong></p>
		</div>
	</div>
	<div class="bottom"></div>
	<div class="row">
		<div class="col-md-12">
			<div style="text-align:center;font-weight:bold;">Invoice Generated On <%= @invoice_created_date %></div>
		</div>
	</div>
</div>

app/views/invoices/unregistered_employee.js.erb
$("#employee_form").html("<%= escape_javascript(render 'employees/form', unregistered_emp_index: @index) %>")

$("#employee_form").find("#new_employee_with_<%= @index %>").modal({
	keyboard: false,
	show: true,
	backdrop: 'static'
});

$('#new_employee_with_<%= @index %>').on('shown.bs.modal', function(){
	$this = $(this)
	$this.find(".modal-body").hide().html("<%= escape_javascript(render 'employees/shared/form_inputs') %>").fadeIn(350)
	
	$(".qualification_note").show()
	$(".family_detail_note").show()

	// Adding Functions To Inputs
	var form = new EmployeeFormDetail(this);
	form.addingClassToInputs();
	
	form.employeeDateSelector($this.find("#employee_dob"));
	form.employeeDateSelector($this.find("#emp_joining_date"));

	form.employeeDateSelector($this.find("#employee_qualification_form").find(".from_date"), "", "year", "yyyy");
	form.employeeDateSelector($this.find("#employee_qualification_form").find(".to_date"), "", "year", "yyyy");
	form.employeeDateSelector($this.find("#employee_family_details_form").find(".family_dob"), "top");
	form.employeeDesignationSelector();
	form.validate();
});



    