config/routes.rb
Rails.application.routes.draw do
  resources :invoices, only: [:index, :update] do
    collection do
      get "invoice_number" => "invoices#get_invoice_number"
      get "synchronisation_of_invoices" => "invoices#synchronisation_of_invoices"
      post "fetch_invoices" => "invoices#fetch_invoices"
      post "custom_invoice" => "invoices#custom_invoice"
      get "new_employee" => "invoices#unregistered_employee"
      get "resync_status" => "invoices#resync_status"
      post "generate_invoices" => "invoices#generate_invoices", :as => :generate
      put "/recalculate" => "invoices#recalculate"
      get "/status", to: "invoices#invoice_status"
    end
  end

  match "invoices/:invoice_created_date" => "invoices#show", via: [:get, :pdf], :as => :invoice_pdf

  resources :employees, :only => [:create] do 
    collection do 
      post "/qualifications/:unregister_emp_id" => "employees#qualifications", as: :qualifications
      post "/family_details/:unregister_emp_id" => "employees#family_details", as: :family_details
      delete "/destroy_qualification/:unregister_emp_id" => "employees#destroy_qualification", as: :remove_qualification
      delete "/destroy_family_detail/:unregister_emp_id" => "employees#destroy_family_detail", as: :remove_family_detail
    end
  end

  namespace :reports do
    get "/" => "base#listing"
    resources :profitability_reports, only: [:index] do
      collection do 
        get "/divisions" => "profitability_reports#divisions_report", as: :divisions
        get "/projects" => "profitability_reports#projects_report", as: :projects
        get "/project" => "profitability_reports#specified_project_report", as: :project
        get "/division_based" => "profitability_reports#specified_division_report", as: :division_based
        get "/designations" => "profitability_reports#designations_report", as: :designations
        get "/employee_history" => "profitability_reports#employee_history_report", as: :employee_history
      end
    end
    resources :re_calculate_reports, only: [:index] do
      collection do 
        post "/calculate_profitability_reports" => "re_calculate_reports#calculate_profitability_reports"
      end
    end
  end

  resources :rates, only: [:index, :create, :update] do
    get "/sync_designations" => "rates#sync_designations", on: :collection
    get "/:designation_id/designation_rate_history" => "rates#designation_rate_history", on: :collection
  end

  resources :projects, only: [:index] do
    get "/sync_projects" => "projects#sync_projects", on: :collection
  end

  devise_for :users
  devise_scope :user do
    get "settings", to: "devise/registrations#edit"
  end

  get 'home/welcome'

  authenticated :user do
    root 'invoices#index', as: :authenticated_root
  end

  unauthenticated :user do
    devise_scope :user do 
      get "/", to: "devise/sessions#new"
    end
  end
end

app/controllers/reports/base_controller.rb
module Reports
	class BaseController < ApplicationController
		before_action :authenticate_user!

		def listing
			respond_to do |format|
				format.html { render :template => "/reports/listing" }
			end
		end

		def generate_profitability_report_for(options = {}, report_name = "", get_report_id = false, &block)

			if get_report_id == true
				ids = []
				options.fetch(:report_for_ids).each do |report|
					ids << report.id
				end
				return ids
			end

			logger.debug "!------Generating #{report_name}--------!"

			@tabular_data = Array.new
			# Revenue
	    @revenue = Array.new
	    revenue_report_array = []
	    profitability_reports = []

	    @revenue << { graph_name: options.has_key?(:graph_label_name) ? "#{options.fetch(:graph_label_name)[0]}" : "Revenue" }
	    options.fetch(:report).each do |report|

	      if block_given?
      		label_name = yield report
	      end

	      data_points = {
      		y: report.amount.to_i,
      		label: label_name   	
	      }
	      revenue_report_array << data_points
	      @tabular_data << data_points
	    end

	    @revenue << { graph_data: revenue_report_array } 
	    @max_ammount = @revenue.second[:graph_data].map{|m| m.values.first}.max{ |a,b| (a || 0) <=> (b || 0) }

			# Expense
			@expense = Array.new
	    expense_report_array = []

	    @expense << { graph_name: options.has_key?(:graph_label_name) ? "#{options.fetch(:graph_label_name)[1]}" : "Expense" }
	    options.fetch(:report).each do |report|

	      if block_given?
      		label_name = yield report
	      end

	      calculated_expense = report.cogs.to_i + report.opexp.to_i
	      data_points = {
      		y: calculated_expense,
      		label: label_name   	
	      }
	      expense_report_array << data_points
	      @tabular_data << data_points
	    end

	    @expense << { graph_data: expense_report_array }
	    @max_calculated_expense = @expense.second[:graph_data].map{|m| m.values.first}.max{ |a,b| (a || 0) <=> (b || 0) }


	    # Profit & Loss
	    @profit = Array.new
	    @loss = Array.new
	    loss_report_array = []
	    profit_report_array = []

	    @loss << { graph_name: options.has_key?(:graph_label_name) ? "#{options.fetch(:graph_label_name)[2]}" : "Loss" }
	    @profit << { graph_name: options.has_key?(:graph_label_name) ? "#{options.fetch(:graph_label_name)[3]}" : "Profit" }


	    options.fetch(:report).each do |report|

	      if block_given?
	      	label_name = yield report
	      end

	      if report.profit.to_f > 0
	        data_points_for_profit = {
	      		y: report.profit.to_i,
	      		label: label_name   	
		      }
		      data_points_for_loss = {
	      		y: 0,
	      		label: label_name   	
		      }
		      loss_report_array << data_points_for_loss
	    		profit_report_array << data_points_for_profit
	      else
	        data_points_for_profit = {
	      		y: 0,
	      		label: label_name   	
		      }
		      data_points_for_loss = {
	      		y: report.profit.to_i.abs,
	      		label: label_name   	
		      }
		      profit_report_array << data_points_for_profit
		      loss_report_array << data_points_for_loss
	      end

	      @tabular_data << data_points_for_profit
	      @tabular_data << data_points_for_loss
	    end

	    @profit << { graph_data: profit_report_array }
      @loss << { graph_data: loss_report_array }

      @max_profit_for_profit = @profit.second[:graph_data].map{|m| m.values.first}.max{ |a,b| (a || 0) <=> (b || 0) }
      @max_profit_for_loss = @loss.second[:graph_data].map{|m| m.values.first}.max{ |a,b| (a || 0) <=> (b || 0) }

      # Tabular Report Grouped By
      @tabular_data = @tabular_data.group_by { |d| d[:label] }
		end
	end
end

app/controllers/reports/profitability_reports_controller.rb
module Reports
	class ProfitabilityReportsController < BaseController
		def index
			if params[:month_year].present?
				@month = params[:month_year].delete(' ').split("-").first
				@year = params[:month_year].delete(' ').split("-").last
			end

			if params[:profit_report] == "true"
				@profitability_reports = ProfitabilityReport.where("month = ? and year = ?", @month, @year)	
			else
				@emp_profitability_reports = Employee::EmployeeProfitibilityReport.where("month = ? and year = ?", @month, @year).order("employee_name")
			end

			@profitability_reports ||= []
			emp_profitability_reports ||= nil

			@dollar_rate = DollarRates.find_by_month_and_year(@month, @year)
			
			respond_to do |format|
				format.js
			end
		end

		def divisions_report
			@month = params[:month_year].present? ? params[:month_year].delete(' ').split("-").first : Date.today.month
			@year = params[:month_year].present? ? params[:month_year].delete(' ').split("-").last : Date.today.year

			@division_report = ProfitabilityReport.divisions_report(@month, @year)

			divisions = Division.all

			# Genrating Divisions Report
			generate_profitability_report_for({:report => @division_report}, :divisions_report) do |report|
				report.div_id.nil? ? "---" : divisions[report.div_id - 1].div_name
			end
		end

		def projects_report
			@month = params[:month_year].present? ? params[:month_year].delete(' ').split("-").first : Date.today.month
			@year = params[:month_year].present? ? params[:month_year].delete(' ').split("-").last : Date.today.year

			# Genrating Projects Report
			@projects_report = ProfitabilityReport.projects_report(@month, @year)
			
			generate_profitability_report_for({:report => @projects_report, :graph_label_name => ["Cogs", "Expenses", "Loss", "Profit"]}, :designations_report) do |report|
				report.project_id.nil? ? "---" : RmProject.get_project_name(report.project_id)
			end
		end
		

		def specified_project_report
			@rm_projects = RmProject.all
			@year = params[:year].present? ? params[:year].delete(' ').split("-").last : Date.today.year
			@project_id = params[:report_project_id].present? ? params[:report_project_id] : @rm_projects.first.project_id

	    @project_name = RmProject.get_project_name @project_id

	    @specific_project_report = ProfitabilityReport.custom_project_report(@project_id, @year)
	    @report_data = Array.new

	    @revenue = Array.new
	    @expense = Array.new
	    @profit = Array.new

	    @tabular_data = Array.new

	    @specific_project_report.each do |project|
	    	calculated_expense = project.cogs.to_f + project.opexp.to_f
	    	data_points_for_r = { amount:  project.amount.to_f, label: "#{I18n.t("date.abbr_month_names")[project.month.to_i]} #{@year}"}
	    	data_points_for_e = { cal_expense:  calculated_expense, label: "#{I18n.t("date.abbr_month_names")[project.month.to_i]} #{@year}"}
	    	data_points_for_p = { profit:  project.profit.to_f, label: "#{I18n.t("date.abbr_month_names")[project.month.to_i]} #{@year}"}
	    	@revenue << data_points_for_r
	    	@expense << data_points_for_e
	    	@profit << data_points_for_p

	    	# Tabular Report
	    	@tabular_data << data_points_for_r << data_points_for_e << data_points_for_p
	    end

	    @tabular_data = @tabular_data.group_by { |d| d[:label] }
		end

		def specified_division_report
			@divisions = Division.all
			@month = params[:month_year].present? ? params[:month_year].delete(' ').split("-").first : Date.today.month
			@year = params[:month_year].present? ? params[:month_year].delete(' ').split("-").last : Date.today.year

			@division_id = params[:report_division_id].present? ? params[:report_division_id] : @divisions.first.id
			@specific_division_report = ProfitabilityReport.custom_division_report(@month, @year, @division_id)

			# Genrating Specific Division Report
			generate_profitability_report_for({:report => @specific_division_report}, :designations_report) do |report|
				report.project_id.nil? ? "---" : RmProject.get_project_name(report.project_id)
			end
		end

		def designations_report
			@month = params[:month_year].present? ? params[:month_year].delete(' ').split("-").first : Date.today.month
			@year = params[:month_year].present? ? params[:month_year].delete(' ').split("-").last : Date.today.year
			@designations_report = ProfitabilityReport.designations_report(@month, @year)

			# Genrating Designations Report
			generate_profitability_report_for({:report => @designations_report}, :designations_report) { |report| report.designation_id.nil? ? "---" : Designation.find(report.designation_id).designation }
		end

		def employee_history_report
			@rm_url = RmService.new
			@rm_projects = RmProject.all
	    @project_id = params[:report_project_id].present? ? params[:report_project_id] : 3
	    @start_date = params[:start_date].present? ? params[:start_date].delete(" ") : Date.today.beginning_of_month.strftime("%b %d, %Y")
	    @end_date = params[:end_date].present? ? params[:end_date].delete(" ") : Date.today.end_of_month.strftime("%b %d, %Y")

	    

	  	@doc = Nokogiri::XML(open(@rm_url.get_employee_history_of_allocations(@project_id, @start_date.delete(" "), @end_date.delete(" "))))
	  	@xml_data = @doc.css("Allocations Allocation")

	  	allocations = Array.new
			total_allocation = []

			total_cost = 0
    	total_revenue = 0
    	total_profit_or_loss = 0	    
	  	@xml_data.each do |history_data|
	  			
	  		project_id = history_data.css('ProjectID').text
	  		emp_id = history_data.css("FOMSID").text
        prorated_percent = history_data.css("ProRated").text

      	month = @start_date.to_date.strftime("%m") 
        year = @start_date.to_date.strftime("%Y")

        emp_report = Employee::EmployeeProfitibilityReport.get_history_report_of(emp_id.to_i, month, year).first
        if emp_report.present?
        	cost = (emp_report.total / 100) * prorated_percent.to_f
          total_cost += cost
        end

        total_invoices = TotalInvoice.get_invoiced_employees(project_id, emp_id.to_i, month, year).first

        if total_invoices.present?
          revenue = (total_invoices.amount / 100) * prorated_percent.to_f
          total_revenue += revenue
        end

        if revenue and cost
        	profit_or_loss = revenue - cost
        	total_profit_or_loss += profit_or_loss
        end
        
        attributes = {
	          :project_id => project_id,
	          :project_name => history_data.css("ProjectName").text,
	          :employee_id => emp_id,
	          :employee_name => history_data.css("Name").text,
	          :billing_type => history_data.css("BillingType").text,
	          :allocation_age => history_data.css("PercentAlloc").text,
	          :start_date => history_data.css("StartDate").text,
	          :end_date => history_data.css("EndDate").text,
	          :prorated => prorated_percent,
	          :cost => cost.nil? ? "---" : cost,
	          :revenue => revenue.nil? ? "---" : revenue,
	          :profit_or_loss => profit_or_loss.nil? ? "---" : profit_or_loss
	        }

        allocations << attributes
      end

	    @rm_project_name = RmProject.get_project_name(params[:report_project_id]) unless params[:report_project_id].blank?

      total_profitability = {
        :project_id => @project_id,
        :project_name => @rm_project_name,
        :total_cost => total_cost,
        :total_revenue => total_revenue,
        :total_profit_or_loss => total_profit_or_loss
      }
      total_allocation << total_profitability

      @summarized_report = total_allocation
      @detailed_report = allocations
		end
	end
end

app/controllers/reports/re_calculate_reports_controller.rb
module Reports
	class ReCalculateReportsController < ApplicationController
		def calculate_profitability_reports
			@month = params[:month].present? ? params[:month] : Date.today.month
			@year = params[:year].present? ? params[:year] : Date.today.year

			begin 
				@record = DollarRates.find_by_month_and_year(@month, @year)
		    dollar_rate = dollar_rate.blank? ? 1 : @record.dollar_rate

		    logger.debug "Dollar Rate: -> #{dollar_rate}"
				# Creating Profitability Reports
				@profitability_reports = ProfitabilityReport.calculate_profitability_report(@month, @year, dollar_rate)

		    # Creating Employee Profitability Reports
		    @emp_profit_report = Employee::EmployeeProfitibilityReport.calculate_emp_profitability_report(@month, @year, dollar_rate)

			rescue *[StandardError, ScriptError, TypeError] => error
				logger.debug "Error: -> #{error}"
				respond_to do |format|
					format.json { render :json => { status: :error, :message => "#{error.message}" }, status: :created }
				end
				return
			else
				respond_to do |format|
					format.json { render :json => { status: :created, :dollar_rate => dollar_rate }, status: :created }
				end
			ensure
  			logger.debug "Recalculated"
			end
		end
	end
end

app/helpers/reports_helper.rb
module ReportsHelper
	MONTH_NAMES = [	
		{"id" => "1", "name" => "January"},
		{"id" => "2", "name" => "Feburary"},
		{"id" => "3", "name" => "March"},
		{"id" => "4", "name" => "April"},
		{"id" => "5", "name" => "May"},
		{"id" => "6", "name" => "June"},
		{"id" => "7", "name" => "July"},
		{"id" => "8", "name" => "August"},
		{"id" => "9", "name" => "September"},
		{"id" => "10", "name" => "October"},
		{"id" => "11", "name" => "November"},
		{"id" => "12", "name" => "December"}
	]
end

app/views/reports/profitability_reports/designations_report.html.erb
<% content_for :reports do %>
	<blockquote>
		<h2>Designations Report</h2>
	</blockquote>

	<div class="row">
		<div class="col-md-6">
			<%= form_tag designations_reports_profitability_reports_path, method: :get do %>
				<p>
					<label>Search Report By Month:</label>
					<%= text_field_tag :month_year, params[:month_year], id: "report_month_year", class: "form-control", placeholder: "Select Date" %>
				</p>
				<p><%= button_tag 'Search', id: "get_report", :class => 'btn btn-danger', data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> Searching"} %>
				<%= link_to "Reset", designations_reports_profitability_reports_path, class: "btn btn-default" %></p>
			<% end %>
		</div>
	</div>
	<ul class="nav nav-tabs">
		<li class="active"><a href="#graph_report" data-toggle="tab" aria-expanded="false">Graph Report</a></li>
	  <li class=""><a href="#tabular_report" data-toggle="tab" aria-expanded="true">Tabular Report</a></li>
	</ul>
	<div id="myTabContent" class="tab-content">
	  <div class="tab-pane fade active in" id="graph_report">
	  	<div class="page-header">
				<h3>Graphical <small>Report</small></h3>
			</div>
	  	<%= render "reports/shared/pie_chart_graph_report", revenue: @revenue, expense: @expense, loss: @loss, profit: @profit, max_ammount: @max_ammount, max_calculated_expense: @max_calculated_expense, max_profit_for_loss_report: @max_profit_for_loss, max_profit_for_profit_report: @max_profit_for_profit %>
	  </div>
	  <div class="tab-pane fade in" id="tabular_report">
	  	<%= render "reports/shared/tabular_report_for_pie_chart", tabular_data: @tabular_data, column_name: "Designation Name" %>	
	  </div>
  </div>
<% end %>

app/views/reports/profitability_reports/divisions_report.html.erb
<% content_for :reports do %>
	<blockquote>
		<h2>Divisions Report</h2>
	</blockquote>
	<div class="row">
		<div class="col-md-6">
			<%= form_tag divisions_reports_profitability_reports_path, method: :get do %>
				<p>
					<label>Search Report By Month:</label>
					<%= text_field_tag :month_year, params[:month_year], id: "report_month_year", class: "form-control", placeholder: "Select Date" %>
				</p>
				<p>
				<%= button_tag 'Search', id: "get_report", :class => 'btn btn-danger', data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> Searching"} %>
				<%= link_to "Reset", divisions_reports_profitability_reports_path, class: "btn btn-default" %></p>
			<% end %>
		</div>
	</div>
	<ul class="nav nav-tabs">
		<li class="active"><a href="#graph_report" data-toggle="tab" aria-expanded="false">Graph Report</a></li>
	  <li class=""><a href="#tabular_report" data-toggle="tab" aria-expanded="true">Tabular Report</a></li>
	</ul>
	<div id="myTabContent" class="tab-content">
	  <div class="tab-pane fade active in" id="graph_report">
	  	<div class="page-header">
				<h3>Graphical <small>Report</small></h3>
			</div>
	  	<%= render "reports/shared/pie_chart_graph_report", revenue: @revenue, expense: @expense, loss: @loss, profit: @profit, max_ammount: @max_ammount, max_calculated_expense: @max_calculated_expense, max_profit_for_loss_report: @max_profit_for_loss, max_profit_for_profit_report: @max_profit_for_profit %>	
	  </div>
	  <div class="tab-pane fade in" id="tabular_report">
	  	<%= render "reports/shared/tabular_report_for_pie_chart", tabular_data: @tabular_data, column_name: "Division Name" %>
	  </div>
  </div>
<% end %>

app/views/reports/profitability_reports/employee_history_report.html.erb
<% content_for :reports do %>
	<blockquote>
		<h2>Employee History Report</h2>
	</blockquote>
	<%= form_tag employee_history_reports_profitability_reports_path, method: :get do %>
		<div class="row">
			<div class="col-md-12">
				<div class="row">
					<div class="col-md-4">
						<%= label_tag "Select Project:" %>
	        	<%= select_tag :report_project_id, options_for_select(@rm_projects.map{|m| [m.name, m.project_id]}, params[:report_project_id]), prompt: "--Select Designation--", class: "form-control" %>
					</div>
					<div class="col-md-4">
						<%= label_tag "Start Date:" %>
	        	<%= text_field_tag :start_date, params[:start_date], :class => "form-control", :placeholder => "Start Date" %>
					</div>
					<div class="col-md-4">
						<%= label_tag "End Date:" %>
	        	<%= text_field_tag :end_date, params[:end_date], :class => "form-control", :placeholder => "End Date" %>
					</div>
				</div>
			</div>
		</div>
		<div class="row">&nbsp;</div>
		<div class="row">
			<div class="col-md-6">
				<%= button_tag 'Search', id: "get_report", :class => 'btn btn-danger', data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> Searching"} %>
				<%= link_to "Reset", employee_history_reports_profitability_reports_path, class: "btn btn-default" %>
			</div>
		</div>
	<% end %>
	<div class="row">&nbsp;</div>
	<ul class="nav nav-tabs">
		<li class="active"><a href="#detailed_report" data-toggle="tab" aria-expanded="false">Detailed Report</a></li>
	  <li class=""><a href="#summarized_report" data-toggle="tab" aria-expanded="true">Summarized Report</a></li>
	</ul>
	<div id="myTabContent" class="tab-content">
	  <div class="tab-pane fade active in" id="detailed_report">
	  	<%= render "reports/shared/detailed_history" %>
	  </div>
	  <div class="tab-pane fade in" id="summarized_report">
	  	<%= render "reports/shared/summarized_history" %>	
	  </div>
  </div>
<% end %>

app/views/reports/profitability_reports/index.js.erb
var $activeElem = $("#profitability_report_modal").find("#reports_tab li")
if ($activeElem.first().hasClass("active")) {
	$(".employees_reports	").empty()
	$(".projects_reports").hide().html("<%= escape_javascript(render '/reports/shared/projects_reports') %>").fadeIn(300);
}
else {
	$(".projects_reports").empty()
	$(".employees_reports").hide().html("<%= escape_javascript(render '/reports/shared/employees_reports') %>").fadeIn(300);
}

setTimeout(function(){
	$('#report_search').find('input#report_month_year').datepicker({
	  format: 'm - yyyy',
	  orientation: 'bottom left',
	  minViewMode: 1
	}).on('changeDate', function(e) {
	  return $(this).datepicker('hide');
	});

	$('.prof_report_table').DataTable({
	  'ordering': false,
	  'info': false,
	  'filter': false,
	  "responsive": true,
	  "iDisplayLength": 10
	});

	$("div#prof_report_dollar_rate blockquote").html("This report was created at Dollar Rate <strong><%= @dollar_rate.dollar_rate unless @dollar_rate.blank? %></strong>")
}, 100);

app/views/reports/profitability_reports/projects_report.html.erb
<% content_for :reports do %>
	<blockquote>
		<h2>Projects Report</h2>
	</blockquote>

	<div class="row">
		<div class="col-md-6">
			<%= form_tag projects_reports_profitability_reports_path, method: :get do %>
				<p>
					<label>Search Report By Month:</label>
					<%= text_field_tag :month_year, params[:month_year], id: "report_month_year", class: "form-control", placeholder: "Select Date" %>
				</p>
				<p><%= button_tag 'Search', id: "get_report", :class => 'btn btn-danger', data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> Searching"} %>
				<%= link_to "Reset", projects_reports_profitability_reports_path, class: "btn btn-default" %></p>
			<% end %>
		</div>
	</div>
	<ul class="nav nav-tabs">
		<li class="active"><a href="#graph_report" data-toggle="tab" aria-expanded="false">Graph Report</a></li>
	  <li class=""><a href="#tabular_report" data-toggle="tab" aria-expanded="true">Tabular Report</a></li>
	</ul>
	<div id="myTabContent" class="tab-content">
	  <div class="tab-pane fade active in" id="graph_report">
	  	<div class="page-header">
				<h3>Graphical <small>Report</small></h3>
			</div>
	  	<%= render "reports/shared/pie_chart_graph_report", revenue: @revenue, expense: @expense, loss: @loss, profit: @profit, max_ammount: @max_ammount, max_calculated_expense: @max_calculated_expense, max_profit_for_loss_report: @max_profit_for_loss, max_profit_for_profit_report: @max_profit_for_profit %>
	  </div>
	  <div class="tab-pane fade in" id="tabular_report">
	  	<%= render "reports/shared/tabular_report_for_pie_chart", tabular_data: @tabular_data, column_name: "Project Data" %>	
	  </div>
  </div>
<% end %>

app/views/reports/profitability_reports/specified_division_report.html.erb
<% content_for :reports do %>
	<blockquote>
		<h2>Division Based Report</h2>
	</blockquote>
	<%= form_tag division_based_reports_profitability_reports_path, method: :get do %>
		<div class="row">
			<div class="col-md-6">
				<div class="row">
					<div class="col-md-6">
						<%= label_tag "Select Report By the month:" %>
						<%= text_field_tag :month_year, params[:month_year], id: "report_month_year", class: "form-control", placeholder: "Select Date" %>
					</div>
					<div class="col-md-6">
						<%= label_tag "Select Project:" %>
	        	<%= select_tag :report_division_id, options_for_select(@divisions.map{|m| [m.div_name, m.id]}, params[:report_division_id]), prompt: "--Select Division--", class: "form-control" %>
					</div>
				</div>
			</div>
		</div>
		<div class="row">&nbsp;</div>
		<div class="row">
			<div class="col-md-6">
				<%= button_tag 'Search', id: "get_report", :class => 'btn btn-danger', data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> Searching"} %>
				<%= link_to "Reset", division_based_reports_profitability_reports_path, class: "btn btn-default" %>
			</div>
		</div>
	<% end %>
	<div class="row">&nbsp;</div>
	<ul class="nav nav-tabs">
		<li class="active"><a href="#graph_report" data-toggle="tab" aria-expanded="false">Graph Report</a></li>
	  <li class=""><a href="#tabular_report" data-toggle="tab" aria-expanded="true">Tabular Report</a></li>
	</ul>
	<div id="myTabContent" class="tab-content">
	  <div class="tab-pane fade active in" id="graph_report">
	  	<div class="page-header">
				<h3>Graphical <small>Report</small></h3>
			</div>
	  	<%= render "reports/shared/pie_chart_graph_report", revenue: @revenue, expense: @expense, loss: @loss, profit: @profit, max_ammount: @max_ammount, max_calculated_expense: @max_calculated_expense, max_profit_for_loss_report: @max_profit_for_loss, max_profit_for_profit_report: @max_profit_for_profit %>
	  </div>
	  <div class="tab-pane fade in" id="tabular_report">
	  	<%= render "reports/shared/tabular_report_for_pie_chart", tabular_data: @tabular_data, column_name: "Division Name" %>	
	  </div>
  </div>
<% end %>

app/views/reports/profitability_reports/specified_project_report.html.erb
<% content_for :reports do %>
	<blockquote>
		<h2>Project Based Report</h2>
	</blockquote>
	<%= form_tag project_reports_profitability_reports_path, method: :get do %>
		<div class="row">
			<div class="col-md-6">
				<div class="row">
					<div class="col-md-6">
						<%= label_tag "Select Project:" %>
	        	<%= select_tag :report_project_id, options_for_select(@rm_projects.map{|m| [m.name, m.project_id]}, params[:report_project_id]), prompt: "--Select Designation--", class: "form-control" %>
					</div>
					<div class="col-md-6">
						<%= label_tag "Select Year:" %>
	        	<%= text_field_tag :year, params[:year], id: "report_year", class: "form-control", placeholder: "Select Year" %>
					</div>
				</div>
			</div>
		</div>
		<div class="row">&nbsp;</div>
		<div class="row">
			<div class="col-md-6">
				<%= button_tag 'Search', id: "get_report", :class => 'btn btn-danger', data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> Searching"} %>
				<%= link_to "Reset", project_reports_profitability_reports_path, class: "btn btn-default" %>
			</div>
		</div>
	<% end %>
	<div class="row">&nbsp;</div>
	<ul class="nav nav-tabs">
		<li class="active"><a href="#graph_report" data-toggle="tab" aria-expanded="false">Graph Report</a></li>
	  <li class=""><a href="#tabular_report" data-toggle="tab" aria-expanded="true">Tabular Report</a></li>
	</ul>
	<div id="myTabContent" class="tab-content">
	  <div class="tab-pane fade active in" id="graph_report">
	  	<div class="page-header">
				<h3>Graphical <small>Report</small></h3>
			</div>
	  	<%= render "reports/shared/line_chart_graph_report", revenue: @revenue, expense: @expense, profit: @profit %>
	  </div>
	  <div class="tab-pane fade in" id="tabular_report">
	  	<%= render "reports/shared/tabular_report_for_line_chart", tabular_data: @tabular_data %>
	  </div>
  </div>
<% end %>